/*
 * DBAddressBuilderDialog.java
 *
 * Created on January 4, 2003, 4:40 PM
 */

package psl.memento.server.frax.gui;

import java.net.URI;
import java.util.*;
import javax.swing.*;
import psl.memento.server.frax.Frax;
import psl.memento.server.dataserver.sql.*;

/**
 *
 * @author  Mark Ayzenshtat
 */
public class DBAddressBuilderDialog extends javax.swing.JDialog {
  private FraxGUI mFraxGUI;
  
  /** Creates new form DBAddressBuilderDialog */
  public DBAddressBuilderDialog(java.awt.Frame parent, boolean modal,
      FraxGUI iFraxGUI) {
    super(parent, modal);
    mFraxGUI = iFraxGUI;
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    radioVendorUnknown = new javax.swing.JRadioButton();
    radioVendorKnown = new javax.swing.JRadioButton();
    ddVendor = new javax.swing.JComboBox();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    tfHostName = new javax.swing.JTextField();
    jPanel6 = new javax.swing.JPanel();
    tfPort = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jPanel7 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    tfUserName = new javax.swing.JTextField();
    jPanel8 = new javax.swing.JPanel();
    tfPassword = new javax.swing.JPasswordField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jPanel9 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    tfDatabase = new javax.swing.JTextField();
    jPanel10 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    tfTable = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();

    setTitle("Database Address Builder");
    setLocationRelativeTo(null);
    setModal(true);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

    jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

    jLabel1.setText("Vendor:");
    jLabel1.setToolTipText("null");
    jLabel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
    jPanel3.add(jLabel1);

    radioVendorUnknown.setSelected(true);
    radioVendorUnknown.setText("Unknown");
    radioVendorUnknown.setToolTipText("");
    buttonGroup1.add(radioVendorUnknown);
    radioVendorUnknown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        radioVendorUnknownActionPerformed(evt);
      }
    });

    jPanel3.add(radioVendorUnknown);

    radioVendorKnown.setText("Known");
    buttonGroup1.add(radioVendorKnown);
    radioVendorKnown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        radioVendorKnownActionPerformed(evt);
      }
    });

    jPanel3.add(radioVendorKnown);

    Map vendorMap = Frax.getInstance().getConfiguration().getDBMSVendorMap();
    Object[] vendors = vendorMap.keySet().toArray();
    Arrays.sort(vendors);
    ddVendor.setModel(new DefaultComboBoxModel(vendors));
    ddVendor.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
    ddVendor.setEnabled(false);
    ddVendor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ddVendorActionPerformed(evt);
      }
    });

    jPanel3.add(ddVendor);

    jPanel1.add(jPanel3);

    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

    jPanel4.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
    jPanel5.setLayout(new java.awt.BorderLayout());

    jLabel2.setDisplayedMnemonic('H');
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Host Name");
    jLabel2.setToolTipText("");
    jPanel5.add(jLabel2, java.awt.BorderLayout.WEST);

    tfHostName.setColumns(15);
    tfHostName.setToolTipText("");
    jPanel5.add(tfHostName, java.awt.BorderLayout.EAST);

    jPanel4.add(jPanel5);

    jPanel6.setLayout(new java.awt.BorderLayout());

    tfPort.setColumns(5);
    tfPort.setToolTipText("");
    jPanel6.add(tfPort, java.awt.BorderLayout.EAST);

    jLabel3.setDisplayedMnemonic('P');
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Port");
    jLabel3.setToolTipText("");
    jPanel6.add(jLabel3, java.awt.BorderLayout.WEST);

    jPanel4.add(jPanel6);

    jPanel7.setLayout(new java.awt.BorderLayout());

    jLabel4.setDisplayedMnemonic('U');
    jLabel4.setText("User Name");
    jPanel7.add(jLabel4, java.awt.BorderLayout.WEST);

    tfUserName.setColumns(15);
    jPanel7.add(tfUserName, java.awt.BorderLayout.EAST);

    jPanel4.add(jPanel7);

    jPanel8.setLayout(new java.awt.BorderLayout());

    tfPassword.setColumns(15);
    jPanel8.add(tfPassword, java.awt.BorderLayout.EAST);

    jLabel5.setDisplayedMnemonic('A');
    jLabel5.setText("Password");
    jPanel8.add(jLabel5, java.awt.BorderLayout.WEST);

    jPanel4.add(jPanel8);

    jLabel6.setFont(new java.awt.Font("Dialog", 0, 10));
    jLabel6.setText("(WARNING: Password will be displayed in address bar of main window.)");
    jPanel4.add(jLabel6);

    jPanel9.setLayout(new java.awt.BorderLayout());

    jLabel7.setDisplayedMnemonic('D');
    jLabel7.setLabelFor(tfDatabase);
    jLabel7.setText("Database");
    jPanel9.add(jLabel7, java.awt.BorderLayout.WEST);

    tfDatabase.setColumns(15);
    jPanel9.add(tfDatabase, java.awt.BorderLayout.EAST);

    jPanel4.add(jPanel9);

    jPanel10.setLayout(new java.awt.BorderLayout());

    jLabel8.setDisplayedMnemonic('T');
    jLabel8.setLabelFor(tfTable);
    jLabel8.setText("Table");
    jPanel10.add(jLabel8, java.awt.BorderLayout.WEST);

    tfTable.setColumns(15);
    jPanel10.add(tfTable, java.awt.BorderLayout.EAST);

    jPanel4.add(jPanel10);

    jPanel1.add(jPanel4);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jButton1.setMnemonic('O');
    jButton1.setText("OK");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jPanel2.add(jButton1);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String hostName = tfHostName.getText().trim();
    String port = tfPort.getText().trim();
    String userName = tfUserName.getText().trim();
    String password = tfPassword.getText().trim();
    String db = tfDatabase.getText().trim();
    String table = tfTable.getText().trim();
    
    StringBuffer sb = new StringBuffer();
    
    // always start with a DB URI
    sb.append("db://");

    if (!userName.equals("")) {
      sb.append(userName);
      if (!password.equals("")) {
        sb.append(':').append(password);
      }
      sb.append('@');
    }

    if (!hostName.equals("")) {
      sb.append(hostName);
      if (!port.equals("")) {
        try {
          Integer.parseInt(port);
        } catch (NumberFormatException ex) {
          JOptionPane.showMessageDialog(getOwner(),
            "Port value must be a number.", "Error",
            JOptionPane.ERROR_MESSAGE);
          return;
        }
        sb.append(':').append(port);
      }
    }
    
    sb.append('/').append(db);
    if (!table.equals("")) {
      sb.append('/').append(table);
    }
    
    if (radioVendorKnown.isSelected()) {
      // build a JDBC URI
      Map vendorMap = Frax.getInstance().getConfiguration().getDBMSVendorMap();
      String vendorName = (String) ddVendor.getSelectedItem();
      
      try {
        String vendorClassName = (String) vendorMap.get(vendorName);
        VendorCoupler vc
          = (VendorCoupler) Class.forName(vendorClassName).newInstance();
        
        sb = new StringBuffer(vc.getJdbcURL(new URI(sb.toString())));
      } catch (Exception ex) {
        JOptionPane.showMessageDialog(getOwner(),
          "Couldn't generate JDBC URI: " + ex.getMessage(), "Error",
          JOptionPane.ERROR_MESSAGE);
      }
    }
    
    mFraxGUI.getAddressTextCombo().setSelectedItem(sb.toString());
    
    setVisible(false);
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void radioVendorUnknownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVendorUnknownActionPerformed
    ddVendor.setEnabled(false);
  }//GEN-LAST:event_radioVendorUnknownActionPerformed

  private void ddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddVendorActionPerformed
    // Add your handling code here:
  }//GEN-LAST:event_ddVendorActionPerformed

  private void radioVendorKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVendorKnownActionPerformed
    ddVendor.setEnabled(true);
  }//GEN-LAST:event_radioVendorKnownActionPerformed
  
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeDialog
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel9;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JTextField tfTable;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton jButton1;
  private javax.swing.JPasswordField tfPassword;
  private javax.swing.JComboBox ddVendor;
  private javax.swing.JRadioButton radioVendorUnknown;
  private javax.swing.JTextField tfHostName;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JRadioButton radioVendorKnown;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JTextField tfPort;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JTextField tfDatabase;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField tfUserName;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
  
}
