/*
 * FTPAddressBuilderDialog.java
 *
 * Created on January 3, 2003, 10:04 AM
 */

package psl.memento.server.frax.gui;

import javax.swing.*;

/**
 *
 * @author  Mark Ayzenshtat
 */
public class FTPAddressBuilderDialog extends javax.swing.JDialog {
  private FraxGUI mFraxGUI;
  
  /** Creates new form FTPAddressBuilderDialog */
  public FTPAddressBuilderDialog(java.awt.Frame parent, boolean modal,
      FraxGUI iFraxGUI) {
    super(parent, modal);
    mFraxGUI = iFraxGUI;
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jPanel2 = new javax.swing.JPanel();
    buttonOK = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfHostName = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    tfPort = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jPanel6 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    tfUserName = new javax.swing.JTextField();
    jPanel7 = new javax.swing.JPanel();
    tfPassword = new javax.swing.JPasswordField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jPanel8 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    tfPath = new javax.swing.JTextField();

    setTitle("FTP Address Builder");
    setLocationRelativeTo(null);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    buttonOK.setMnemonic('O');
    buttonOK.setText("OK");
    buttonOK.setToolTipText("");
    buttonOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonOKActionPerformed(evt);
      }
    });

    jPanel2.add(buttonOK);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    jPanel5.setLayout(new java.awt.BorderLayout());

    jPanel5.setToolTipText("");
    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

    jPanel3.setLayout(new java.awt.BorderLayout());

    jLabel1.setDisplayedMnemonic('H');
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setLabelFor(tfHostName);
    jLabel1.setText("Host Name");
    jLabel1.setToolTipText("");
    jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);

    tfHostName.setColumns(15);
    tfHostName.setToolTipText("");
    jPanel3.add(tfHostName, java.awt.BorderLayout.EAST);

    jPanel1.add(jPanel3);

    jPanel4.setLayout(new java.awt.BorderLayout());

    tfPort.setColumns(5);
    tfPort.setText("21");
    tfPort.setToolTipText("");
    jPanel4.add(tfPort, java.awt.BorderLayout.EAST);

    jLabel2.setDisplayedMnemonic('P');
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setLabelFor(tfPort);
    jLabel2.setText("Port");
    jLabel2.setToolTipText("");
    jPanel4.add(jLabel2, java.awt.BorderLayout.WEST);

    jPanel1.add(jPanel4);

    jPanel6.setLayout(new java.awt.BorderLayout());

    jLabel3.setDisplayedMnemonic('U');
    jLabel3.setLabelFor(tfUserName);
    jLabel3.setText("User Name");
    jPanel6.add(jLabel3, java.awt.BorderLayout.WEST);

    tfUserName.setColumns(15);
    jPanel6.add(tfUserName, java.awt.BorderLayout.EAST);

    jPanel1.add(jPanel6);

    jPanel7.setLayout(new java.awt.BorderLayout());

    tfPassword.setColumns(15);
    jPanel7.add(tfPassword, java.awt.BorderLayout.EAST);

    jLabel4.setDisplayedMnemonic('A');
    jLabel4.setLabelFor(tfPassword);
    jLabel4.setText("Password");
    jPanel7.add(jLabel4, java.awt.BorderLayout.WEST);

    jPanel1.add(jPanel7);

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 10));
    jLabel5.setText("(WARNING: Password will be displayed in address bar of main window.)");
    jPanel1.add(jLabel5);

    jPanel8.setLayout(new java.awt.BorderLayout());

    jLabel6.setDisplayedMnemonic('R');
    jLabel6.setLabelFor(tfPath);
    jLabel6.setText("Remote Path");
    jPanel8.add(jLabel6, java.awt.BorderLayout.WEST);

    tfPath.setColumns(15);
    jPanel8.add(tfPath, java.awt.BorderLayout.EAST);

    jPanel1.add(jPanel8);

    jPanel5.add(jPanel1, java.awt.BorderLayout.NORTH);

    getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

    pack();
  }//GEN-END:initComponents

  private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
    String hostName = tfHostName.getText().trim();
    String port = tfPort.getText().trim();
    String userName = tfUserName.getText().trim();
    String password = tfPassword.getText().trim();
    String path = tfPath.getText().trim();
    
    StringBuffer sb = new StringBuffer();
    sb.append("ftp://");
    if (!userName.equals("")) {
      sb.append(userName);
      if (!password.equals("")) {
        sb.append(':').append(password);
      }
      sb.append('@');
    }

    if (!hostName.equals("")) {
      sb.append(hostName);
      try {
        Integer.parseInt(port);
      } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(getOwner(),
          "Port value must be a number.", "Error",
          JOptionPane.ERROR_MESSAGE);
        return;
      }
      sb.append(':').append(port);
    }
    
    if (!path.startsWith("/")) {
      sb.append('/');
    }
    
    sb.append(path);
    
    mFraxGUI.getAddressTextCombo().setSelectedItem(sb.toString());
    
    setVisible(false);
    dispose();
  }//GEN-LAST:event_buttonOKActionPerformed
  
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeDialog
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField tfPath;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPasswordField tfPassword;
  private javax.swing.JTextField tfHostName;
  private javax.swing.JTextField tfPort;
  private javax.swing.JButton buttonOK;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField tfUserName;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
  
}
