package psl.memento.server.vem;

import javax.swing.*;
import java.io.File;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

/*
 * RoomViewer.java
 *
 * Created on November 6, 2002, 9:19 PM
 */

/**
 *
 * @author  vlad
 */
public class RoomViewer extends javax.swing.JFrame
    implements LayoutParameters {
	
    private File mChoosenFile;
    private LayoutClassManager lcm;
    private int spacingValue;	
    private DataReader dr;
    
    /** Creates new form RoomViewer */
    public RoomViewer() {
        super("Room Viewer");
	
        initComponents();   

	lcm = new LayoutClassManager(this);	
	lcm.addOption(simpleLayoutButton, "Layout");
	lcm.addOption(advancedLayoutButton, "AdvancedLayout");
	
	spacingValue = getSpacingValue();
        setSize(800, 700);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        chooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        drawPane = new DrawPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        spacingSlider = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        highlightCheckbox = new javax.swing.JCheckBox();
        updateButton = new javax.swing.JButton();
        legendScrollPane = new javax.swing.JScrollPane();
        legendPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roomSizeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cellSizeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spaceLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        layoutLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        simpleLayoutButton = new javax.swing.JRadioButtonMenuItem();
        advancedLayoutButton = new javax.swing.JRadioButtonMenuItem();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Room File:");
        jPanel1.add(jLabel1);

        fileTextField.setColumns(25);
        fileTextField.setText("d:\\layout\\room.txt");
        fileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTextFieldActionPerformed(evt);
            }
        });

        jPanel1.add(fileTextField);

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jPanel1.add(loadButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(drawPane, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        textArea.setColumns(20);
        textArea.setRows(15);
        jScrollPane1.setViewportView(textArea);

        jPanel2.add(jScrollPane1);

        spacingSlider.setMajorTickSpacing(1);
        spacingSlider.setMaximum(6);
        spacingSlider.setPaintLabels(true);
        spacingSlider.setPaintTicks(true);
        spacingSlider.setSnapToTicks(true);
        spacingSlider.setValue(2);
        spacingSlider.setBorder(new javax.swing.border.TitledBorder("Max Spacing Factor"));
        spacingSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spacingSliderStateChanged(evt);
            }
        });

        jPanel2.add(spacingSlider);

        highlightCheckbox.setText("Highlight Free Space");
        highlightCheckbox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        highlightCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                highlightCheckboxItemStateChanged(evt);
            }
        });

        jPanel4.add(highlightCheckbox);

        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        jPanel4.add(updateButton);

        jPanel2.add(jPanel4);

        legendScrollPane.setBorder(null);
        legendPanel.setLayout(new java.awt.GridLayout(0, 2, 3, 3));

        legendPanel.setBorder(new javax.swing.border.TitledBorder("Legend"));
        legendScrollPane.setViewportView(legendPanel);

        jPanel2.add(legendScrollPane);

        jPanel3.setLayout(new java.awt.GridLayout(0, 2));

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Properties"));
        jLabel2.setText("Room Dimension:");
        jPanel3.add(jLabel2);

        roomSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(roomSizeLabel);

        jLabel3.setText("Cell Size:");
        jPanel3.add(jLabel3);

        cellSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(cellSizeLabel);

        jLabel4.setText("Space Util.:");
        jPanel3.add(jLabel4);

        spaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(spaceLabel);

        jLabel9.setText("Layout:");
        jPanel3.add(jLabel9);

        layoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(layoutLabel);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jMenu1.setText("Action");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        openItem.setText("Open...");
        openItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openItemActionPerformed(evt);
            }
        });

        jMenu1.add(openItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Layout");
        simpleLayoutButton.setText("Simple");
        jMenu2.add(simpleLayoutButton);

        advancedLayoutButton.setText("Advanced");
        jMenu2.add(advancedLayoutButton);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
	// Add your handling code here:
	if (dr == null)
	    dr = new DataReader(null);
	
	dr.setFileContent(textArea.getText());
	dr.parseInput();
	updateDrawPanel();
    }//GEN-LAST:event_updateButtonMouseClicked

    private void highlightCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_highlightCheckboxItemStateChanged
	// Add your handling code here:
	updateDrawPanel();
    }//GEN-LAST:event_highlightCheckboxItemStateChanged

    private void spacingSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spacingSliderStateChanged
	// Add your handling code here:
	if (getSpacingValue() != spacingValue) {
	    spacingValue = getSpacingValue();
	    updateDrawPanel();
	}
    }//GEN-LAST:event_spacingSliderStateChanged

    private void fileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTextFieldActionPerformed
	// Add your handling code here:
    }//GEN-LAST:event_fileTextFieldActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // Add your handling code here:

	dr = new DataReader(fileTextField.getText());
	if (dr.getRoomData()) {
	    updateDrawPanel();
	} else {
	    DrawPanel dp = (DrawPanel)drawPane;
	    dp.doError(dr.getError());	
	}
	    
    }//GEN-LAST:event_loadButtonActionPerformed

    private void openItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openItemActionPerformed
        // Add your handling code here:
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            mChoosenFile = chooser.getSelectedFile();
            fileTextField.setText(mChoosenFile.getPath());
       }
    }//GEN-LAST:event_openItemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    void updateDrawPanel()
    {
	if (dr == null) return;
	
	DrawPanel dp = (DrawPanel)drawPane;
	Layout layout;
	Hashtable colorHash;
	
	// choosen layout scheme
	layout = lcm.getLayoutInstance(); 
	layout.init(dr, this);

	dp.clear();
	dp.handleInput((LayoutDrawer)layout);

	textArea.setText(dr.getFileContent());
	layoutLabel.setText(layout.getLayoutSchemeName());
	roomSizeLabel.setText(layout.getRoomSize());
	cellSizeLabel.setText(layout.getCellSize());
	spaceLabel.setText(layout.getSpaceUtil());

	colorHash = layout.getLegend();
	legendPanel.removeAll();
	Enumeration e = colorHash.keys();
	String key;
	JPanel p;
	JLabel label;
	while(e.hasMoreElements()) {
	    key = (String) e.nextElement();
	    label = new JLabel(key);
	    label.setHorizontalAlignment(SwingConstants.RIGHT);
	    legendPanel.add(label);
	    p = new JPanel();
	    p.setBackground((Color)colorHash.get(key));
	    legendPanel.add(p);
	}
	legendPanel.revalidate();
    }
    
    public int getSpacingValue()
    {
	return spacingSlider.getValue();
    }
    
    public boolean highlightFreeSpace()
    {
	return highlightCheckbox.isSelected();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new RoomViewer().show();
    }
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem simpleLayoutButton;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JButton loadButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel layoutLabel;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel cellSizeLabel;
    private javax.swing.JSlider spacingSlider;
    private javax.swing.JPanel legendPanel;
    private javax.swing.JCheckBox highlightCheckbox;
    private javax.swing.JLabel roomSizeLabel;
    private javax.swing.JMenuItem openItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel drawPane;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JLabel spaceLabel;
    private javax.swing.JScrollPane legendScrollPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JRadioButtonMenuItem advancedLayoutButton;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
