/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder */

#ifndef _Included_psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder
#define _Included_psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: conversationTextValidChars */
/*
 * Class:     psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder
 * Method:    addConversationWord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder_addConversationWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder
 * Method:    resetConversationHistory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder_resetConversationHistory
  (JNIEnv *, jobject);

/*
 * Class:     psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_psl_memento_pervasive_recommendation_keywordfinder_jebara_impKeywordFinder_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
