package aether.server.responder;

import aether.event.Response;
import aether.event.Request;
import aether.server.framework.Identifiable;

/**
 * A Responder is an object that will process requests and generate responses.
 * In order for Responders to receive requests they must utilize the
 * Switchboard service.
 *
 * @author Buko O. (buko@concedere.net)
 * @version 0.1
 **/
public interface Responder
{
	/**
	 * Proces an incoming request by setting variables on the approriate
	 * response.
	 *
	 * @param request  incoming request to be processed
	 * @param response response to be sent back
	 * @throws ResponderException
	 *         if a component-level error occurs
	 */
	public void respond(Request request, Response response)
			throws ResponderException;

    /**
     * Get the unique ResponderID. This ResponderID will be used to establish
     * the source of the responses generated by this Responder.
     *
     * @return unique responder ID
     */
    public String getResponderId();

}
