/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class psl_ai2tv_client_AI2TVJNIJava */

#ifndef _Included_psl_ai2tv_client_AI2TVJNIJava
#define _Included_psl_ai2tv_client_AI2TVJNIJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     psl_ai2tv_client_AI2TVJNIJava
 * Method:    loadFrame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_psl_ai2tv_client_AI2TVJNIJava_loadFrame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     psl_ai2tv_client_AI2TVJNIJava
 * Method:    displayFrame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_psl_ai2tv_client_AI2TVJNIJava_displayFrame
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
