 /*
 *
 * Copyright (c) 2002: The Trustees of Columbia University
 *    in the City of New York.  All Rights Reserved.
 *
 *
 */

#include "cssysdef.h"
#include "cssys/sysdriv.h"
#include "csws/csws.h"
#include "csver.h"
#include "ivideo/fontserv.h"
#include "ChimeWindowToolkit.h"
#include "ChimeSystemDriver.h"

// The global pointer to ChimeSystemDriver
extern ChimeSystemDriver *driver;

//------------------------------------------//
//---- HistoryBoxItem implementation -------//
//------------------------------------------//

HistoryBoxItem::HistoryBoxItem (csComponent *iParent, 
		const char *iSectorName, const char *iSectorSource, 
		int iID, csListBoxItemStyle iStyle)
		: csListBoxItem (iParent, iSectorName, iID, iStyle)
{
	strSectorName = (char*) malloc (100 * sizeof(char));
	strSectorSource = (char*) malloc (100 * sizeof(char));

	strcpy (strSectorName, iSectorName);
	strcpy (strSectorSource, iSectorSource);

	csItemHint = NULL;
}

void HistoryBoxItem::ShowHint ()
{
	char hint_text [200];
	strcpy (hint_text, strSectorName);
	strcat (hint_text, " @ ");
	strcat (hint_text, strSectorSource);
	csItemHint = new csHint (this, hint_text);
	csItemHint->Show ();
}

void HistoryBoxItem::HideHint ()
{
	if (!csItemHint)
		return;

	csItemHint->Hide ();
	csItemHint->Close ();
	csItemHint = NULL;
}

bool HistoryBoxItem::HandleEvent (iEvent &Event)
{
	/**
	switch (Event.Type)
	{
	case csevMouseDown:
		if (Event.Mouse.Button == 2) ShowHint ();
		break;
	case csevMouseUp:
		if (Event.Mouse.Button == 2) HideHint ();
		break;
	case csevMouseMove:
		HideHint ();
		break;
	}
	*/

	return csListBoxItem::HandleEvent (Event);
}


//------------------------------------------//
//---- History Window implementation -------//
//------------------------------------------//

// Scroll bar class default palette
ChimeHistoryWindow::~ChimeHistoryWindow() {}


ChimeHistoryWindow::ChimeHistoryWindow(csComponent *iParent)
  : csWindow(iParent, " History ", CSWS_TITLEBAR, cswfsThin)
  {

  SetRect (1, 1, app->bound.Width() / 4, app->bound.Height() / 3);

  int px = 15, py = 20;
  int labelw = 150;

  //////////create the dialog///////////////
  csDialog *d = new csDialog(this);
  this->SetDragStyle (this->GetDragStyle () & ~CS_DRAG_SIZEABLE);
  
  //////////create the list box/////////////
  list_box = new csListBox (d, CSLBS_HSCROLL | CSLBS_VSCROLL, cslfsThinRect);
  list_box->SetRect (bound.Width() / 10, 1,  bound.Width() / 10 * 9, bound.Height() / 2 - 1);

  //setup the "Go There"
  csButton *GoBut = new csButton(d, HISTORY_GO_THERE_PRESSED);
  GoBut->SetText("GO THERE");
  GoBut->SetSize(bound.Width ()/2, bound.Height() / 3);
  GoBut->SetPos(bound.Width ()/4, bound.Height() / 2 + 1);
  
  selected_item = NULL;
  item_list = new csVector (8);
}

//Add an item to the History Box
bool ChimeHistoryWindow::AddItem (char *iSectorName, char *iSectorSource) {

	if (FindItem (iSectorName, iSectorSource))
		return false;
	selected_item = new HistoryBoxItem (list_box, iSectorName, iSectorSource);
	item_list->Push (selected_item);
	return true;
}

//Find list item corresponding to the parameters
HistoryBoxItem* ChimeHistoryWindow::FindItem (char *iSectorName, char *iSectorSource)
{
	HistoryBoxItem *item = NULL;
	for (int i = 0; i < item_list->Length (); i++)
	{
		item = (HistoryBoxItem*) item_list->Get (i);
		if (!strcmp (iSectorName, item->GetSectorName ()) && 
			!strcmp (iSectorSource, item->GetSectorSource ()))
			return item;
	}
	return NULL;
}

//Handle and Event generated by the History Window
bool ChimeHistoryWindow::HandleEvent (iEvent &Event)
{

  if (csWindow::HandleEvent (Event))
    return true;

  if (Event.Type == csevCommand)
  {
      switch (Event.Command.Code)
      {
		case cscmdListBoxItemClicked:
		case cscmdListBoxItemSelected:
			selected_item = (HistoryBoxItem*) Event.Command.Info;
			return true;

        case HISTORY_GO_THERE_PRESSED:
			if (selected_item) 
			{
				driver->TransportToSector (selected_item->GetSectorName (), 
					selected_item->GetSectorSource ());
			}
		return true;
	  }
  }

  return false;
}
